// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ2rdp2m1NGmp3nG-lHRsv23KhInDwBfo',
    appId: '1:333750750744:web:65237eac73f69841c53d6d',
    messagingSenderId: '333750750744',
    projectId: 'homerepair-beni-romain',
    authDomain: 'homerepair-beni-romain.firebaseapp.com',
    storageBucket: 'homerepair-beni-romain.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6BuYc81_2nUTkXP30VEvlAeW3zbg9qRI',
    appId: '1:333750750744:android:eaeb2bf85bda07cac53d6d',
    messagingSenderId: '333750750744',
    projectId: 'homerepair-beni-romain',
    storageBucket: 'homerepair-beni-romain.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3UzbBG_9XjEdq7UDCNmgacmEPfvGJrek',
    appId: '1:333750750744:ios:2009b3af39861f08c53d6d',
    messagingSenderId: '333750750744',
    projectId: 'homerepair-beni-romain',
    storageBucket: 'homerepair-beni-romain.appspot.com',
    iosClientId: '333750750744-qe2vi6an6igf243utuie32c51rfv5t6a.apps.googleusercontent.com',
    iosBundleId: 'com.homerepair-beni-rom.app',
  );
}
